version: '3.3'

services:
  soltec_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soltec_backend
    environment:
      - VIRTUAL_HOST=betel-api.tecnologiaydesarrollo.net
      - LETSENCRYPT_HOST=betel-api.tecnologiaydesarrollo.net
      - LETSENCRYPT_EMAIL=onlin1992@gmail.com
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - webnet

  soltec_frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: soltec_frontend
    environment:
      - VIRTUAL_HOST=betel.tecnologiaydesarrollo.net
      - LETSENCRYPT_HOST=betel.tecnologiaydesarrollo.net
      - LETSENCRYPT_EMAIL=onlin1992@gmail.com
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    name: proxynet
    external: true
