import { ClienteDto } from './cliente.dto';
import { DetalleDeFacturaDto } from './detalle-de-factura.dto';
import { DocumentoReferenciadoDto } from './documento-referenciado.dto';
import { EntregaMercanciaDto } from './entrega-mercancia.dto';
import { ExtrasDto } from './extras.dto';
import { FacturaImpuestosDto } from './factura-impuestos.dto';
import { ImpuestosTotalesDto } from './impuestos-totales.dto';
import { MediosDePagoDto } from './medios-de-pago.dto';
import { OrdenDeCompraDto } from './orden-de-compra.dto';
import { TasaDeCambioDto } from './tasa-de-cambio.dto';
import { TasaDeCambioAlternativaDto } from './tasa-de-cambio-alternativa.dto';
import { TerminosEntregaDto } from './terminos-entrega.dto';
import { AnticipoDto } from './anticipo.dto';
import { AutorizadoDto } from './autorizado.dto';
import { CargoDescuentoDto } from './cargo-descuento.dto';
import { CondicionPagoDto } from './condicion-pago.dto';
import { LineaInformacionAdicionalDto } from './linea-informacion-adicional.dto';

export class FacturaGeneralDto {
  cliente: ClienteDto;
  detalleDeFactura: DetalleDeFacturaDto[];
  documentoReferenciado?: DocumentoReferenciadoDto[];
  entrega?: EntregaMercanciaDto;
  extras?: ExtrasDto;
  facturaImpuestos?: FacturaImpuestosDto[];
  impuestosTotales: ImpuestosTotalesDto[];
  informacionAdicional?: LineaInformacionAdicionalDto[];
  mediosDePago: MediosDePagoDto[];
  moneda: string;
  ordenDeCompra?: OrdenDeCompraDto[];
  rangoNumeracion: string;
  redondeoAplicado?: number;
  subtotal: number;
  tasaDeCambio?: TasaDeCambioDto;
  tasaDeCambioAlternativa?: TasaDeCambioAlternativaDto;
  terminosEntrega?: TerminosEntregaDto;
  tipoDocumento: string;
  tipoOperacion: string;
  total: number;
  totalAnticipos?: number;
  totalBaseImponible: number;
  totalBrutoConImpuestos: number;
  totalCargos?: number;
  totalDescuentos?: number;
  totalSinImpuestos: number;
  version?: string;
  anticipos?: AnticipoDto[];
  autorizado?: AutorizadoDto;
  cargosDescuentos?: CargoDescuentoDto[];
  condicionesDePago?: CondicionPagoDto[];
  contingencia?: boolean;
  consecutivoDocumento: string;
  fechaEmision: string;
  fechaVencimiento: string;
} 